// The sample run for the bundled CO2 file: the answers the desk's skills give,
// written in advance so "Try the CO2 sample" runs the whole flow with no key.
// tests/sample-run.test.ts checks every draft with the real fact-check gate and
// writes public/replay/co2_by_country_1990_2024.json. Numbers come only from the
// engine's fact book for each story (ids below are that story's F-numbers).

export const intake = {
  summary:
    'This file tracks how much carbon dioxide (CO₂) each country releases every year, from 1990 to 2024: 218 countries and territories, one row per country per year. For each one it gives the total (in million tonnes) and the amount per person (in tonnes). The figures come from the Global Carbon Budget, published through Our World in Data.',
  roles_ok: true,
  role_notes: '',
  warnings: [
    {
      flag: 'One-period spike: `co2_per_capita` for Kuwait in 1991',
      plain: "Kuwait's 1991 figure is more than 12 times its normal level. That is the year Kuwait's oil wells were set on fire in the Gulf War. It is real but a one-off, so no story ranks countries on that year.",
    },
    {
      flag: 'The highest `consumption_co2_per_capita` belongs to Qatar',
      plain: 'Very small countries can top per-person lists. The desk only ranks per-person figures for places with at least 1 million people.',
    },
    {
      flag: '`consumption_co2` is 47% empty',
      plain: 'A few columns (GDP, emissions counting imports) stop earlier or have gaps. Stories that use them say which year they end.',
    },
  ],
  questions: [
    'Is 2024 a final figure or a first estimate that may be revised?',
    'Which comparison matters most to our readers: totals, or per person?',
  ],
}

export const finder = {
  top: [
    { id: 'S1', headline: 'China now emits more CO₂ per person than Japan or Germany', why: 'A clear turning point between big, familiar countries, with exact years it happened.' },
    { id: 'S3', headline: "Vietnam's CO₂ emissions grew 17.4 times since 1990", why: 'The fastest rise among the 41 largest emitters; striking and easy to picture.' },
    { id: 'S7', headline: 'Five countries account for 62% of CO₂ emissions', why: 'Shows how concentrated the problem is; a strong context story.' },
  ],
  hidden: [
    { id: 'S2', headline: "Counting imports, the UK's emissions fell 27%, not 49%", why: 'Turns a success story around.', why_missed: 'The usual tables count only what is made inside a country. Counting what it imports tells a different story.' },
    { id: 'S9', headline: 'India is the third-biggest emitter, but low per person', why: 'Directly relevant to Indian readers.', why_missed: 'Totals and per-person figures are usually reported separately. Side by side, they point in opposite directions.' },
    { id: 'S5', headline: 'Indonesia climbed from 25th to 6th biggest emitter', why: 'A big mover few readers know about.', why_missed: 'Percentage rankings reward small starting points. A steady climb up the table only shows when you rank the totals.' },
  ],
  dropped: [
    { id: 'S4', reason: "Ukraine's fall comes from economic collapse and war, not climate policy. The UK story is covered better by the imports lead." },
    { id: 'S14', reason: 'Repeats the Vietnam story; Qatar starts from a very small base.' },
    { id: 'S12', reason: 'Per-person extremes are driven by small oil states; less relevant to readers.' },
    { id: 'S15', reason: 'One year is not a trend.' },
  ],
  note: 'Lead with China per person; the India lead is the strongest local angle.',
}

type C = Record<string, unknown>

const SRC = 'the Global Carbon Budget'

export const writers: Record<string, { en: C; ml: C }> = {
  // ---------------- S1 crossover: China per person ----------------
  'crossover:China': {
    en: {
      kicker: 'Climate data',
      headline: 'China now emits more CO₂ per person than Japan or Germany',
      dek: 'CO₂ emissions per person, tonnes, 1990 to 2024',
      body: [
        `The average person in China now emits more carbon dioxide than the average person in Japan or Germany, according to ${SRC}. In 2024 China emitted 8.7 tonnes per person, up from 2.2 tonnes in 1990, 4.0 times as much.`,
        'China passed Germany in 2022 and Japan in 2023. In 1990 the average German emitted 13.2 tonnes and the average Japanese 9.4; by 2024 those figures had fallen to 6.8 and 7.8 tonnes.',
        "China's total is in a different league: 12,289 million tonnes in 2024, 4.9 times its 1990 level.",
        'Per person, China is still well behind the United States, where the average person emitted 14.2 tonnes in 2024, down from 20.3 in 1990.',
        "Per-person figures rest on each year's population estimate, so the crossover years can move if the data is revised.",
      ],
      big_number: { fact_id: 'F2', value: '8.7 tonnes', caption: 'CO₂ per person in China, 2024' },
      key_points: ['8.7 tonnes per person in 2024, up from 2.2 in 1990', 'Passed Germany in 2022 and Japan in 2023', 'Still behind the United States at 14.2 tonnes'],
      qa: [
        { q: 'How fast did it happen?', a: "China's emissions per person grew 4.0 times between 1990 and 2024." },
        { q: 'Is China now the biggest emitter per person?', a: 'No. The average person in the United States emitted 14.2 tonnes in 2024.' },
        { q: 'What about the total?', a: 'China emitted 12,289 million tonnes in 2024, 4.9 times its 1990 level.' },
      ],
      then_now: { then_label: '1990', then_text: 'China emitted 2.2 tonnes per person, far below Japan (9.4) and Germany (13.2).', now_label: '2024', now_text: 'China emits 8.7 tonnes per person, more than Japan (7.8) and Germany (6.8).' },
      timeline: [
        { year: '1990', text: 'China at 2.2 tonnes per person' },
        { year: '2022', text: 'China passes Germany' },
        { year: '2023', text: 'China passes Japan' },
        { year: '2024', text: 'China at 8.7 tonnes per person' },
      ],
      slides: [
        { kicker: 'Climate data', headline: 'China now out-emits Japan and Germany, per person', body: '' },
        { kicker: 'In 2024', headline: 'The average person in China', body: 'emitted 8.7 tonnes of CO₂.', fact_id: 'F2' },
        { kicker: 'In 1990', headline: 'It was a quarter of that', body: 'The average person in China emitted 2.2 tonnes.', fact_id: 'F1' },
        { kicker: 'Japan, 2024', headline: 'Japan has fallen behind', body: 'The average person in Japan emitted 7.8 tonnes.', fact_id: 'F5' },
        { kicker: 'Germany, 2024', headline: 'So has Germany', body: 'The average German emitted 6.8 tonnes.', fact_id: 'F8' },
        { kicker: 'What it means', headline: 'Still behind the US', body: 'The average American emitted 14.2 tonnes in 2024.' },
      ],
      chart_title: 'China passed Japan and Germany per person',
      chart_subtitle: 'CO₂ emissions per person, tonnes, 1990-2024',
      alt_text: 'Line chart: China rose from 2.2 to 8.7 tonnes per person between 1990 and 2024, passing Germany (6.8) and Japan (7.8).',
      caveat: "Per-person figures depend on each year's population estimate.",
      facts_used: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F11', 'F12', 'F15', 'F16'],
    },
    ml: {
      kicker: 'കാലാവസ്ഥ',
      headline: 'ആളോഹരി കാർബൺ ബഹിർഗമനം: ജപ്പാനെയും ജർമ്മനിയെയും ചൈന മറികടന്നു',
      dek: 'ആളോഹരി CO₂ ബഹിർഗമനം, ടണ്ണിൽ, 1990 മുതൽ 2024 വരെ',
      body: [
        'ശരാശരി ഒരു ചൈനക്കാരൻ ഇപ്പോൾ ജപ്പാൻകാരനെക്കാളും ജർമ്മൻകാരനെക്കാളും കൂടുതൽ കാർബൺ ഡൈ ഓക്സൈഡ് പുറന്തള്ളുന്നുവെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. 2024-ൽ ചൈനയുടെ ആളോഹരി ബഹിർഗമനം 8.7 ടൺ ആയിരുന്നു. 1990-ൽ ഇത് 2.2 ടൺ മാത്രമായിരുന്നു; 4.0 മടങ്ങ് വർധന.',
        '2022-ൽ ജർമ്മനിയെയും 2023-ൽ ജപ്പാനെയും ചൈന മറികടന്നു. 1990-ൽ ഒരു ജർമ്മൻകാരന്റെ ശരാശരി ബഹിർഗമനം 13.2 ടണ്ണും ജപ്പാൻകാരന്റേത് 9.4 ടണ്ണുമായിരുന്നു; 2024-ൽ ഇത് യഥാക്രമം 6.8, 7.8 ടണ്ണായി കുറഞ്ഞു.',
        'ആകെ ബഹിർഗമനത്തിൽ ചൈന ഏറെ മുന്നിലാണ്: 2024-ൽ 1,229 കോടി ടൺ, 1990-ലേതിന്റെ 4.9 മടങ്ങ്.',
        'എങ്കിലും ആളോഹരി കണക്കിൽ ചൈന ഇപ്പോഴും അമേരിക്കയെക്കാൾ ഏറെ പിന്നിലാണ്. 2024-ൽ ഒരു അമേരിക്കക്കാരന്റെ ശരാശരി ബഹിർഗമനം 14.2 ടൺ; 1990-ൽ ഇത് 20.3 ടൺ ആയിരുന്നു.',
        'ആളോഹരി കണക്കുകൾ ഓരോ വർഷത്തെയും ജനസംഖ്യാ അനുമാനത്തെ ആശ്രയിച്ചാണ്. ഡാറ്റ പുതുക്കിയാൽ മറികടന്ന വർഷങ്ങൾ മാറാം.',
      ],
      big_number: { fact_id: 'F2', value: '8.7 ടൺ', caption: '2024-ൽ ഒരു ചൈനക്കാരന്റെ ശരാശരി CO₂ ബഹിർഗമനം' },
      key_points: ['2024-ൽ ആളോഹരി 8.7 ടൺ; 1990-ൽ 2.2 ടൺ', '2022-ൽ ജർമ്മനിയെയും 2023-ൽ ജപ്പാനെയും മറികടന്നു', 'അമേരിക്ക (14.2 ടൺ) ഇപ്പോഴും മുന്നിൽ'],
      qa: [
        { q: 'എത്ര വേഗത്തിലായിരുന്നു വളർച്ച?', a: '1990 മുതൽ 2024 വരെ ചൈനയുടെ ആളോഹരി ബഹിർഗമനം 4.0 മടങ്ങായി.' },
        { q: 'ആളോഹരിയിൽ ചൈനയാണോ മുന്നിൽ?', a: 'അല്ല. 2024-ൽ ഒരു അമേരിക്കക്കാരൻ ശരാശരി 14.2 ടൺ പുറന്തള്ളി.' },
        { q: 'ആകെ ബഹിർഗമനമോ?', a: '2024-ൽ ചൈനയുടെ ആകെ ബഹിർഗമനം 1,229 കോടി ടൺ; 1990-ലേതിന്റെ 4.9 മടങ്ങ്.' },
      ],
      then_now: { then_label: '1990', then_text: 'ചൈന ആളോഹരി 2.2 ടൺ; ജപ്പാൻ 9.4, ജർമ്മനി 13.2.', now_label: '2024', now_text: 'ചൈന ആളോഹരി 8.7 ടൺ; ജപ്പാൻ 7.8, ജർമ്മനി 6.8.' },
      timeline: [
        { year: '1990', text: 'ചൈന ആളോഹരി 2.2 ടൺ' },
        { year: '2022', text: 'ജർമ്മനിയെ മറികടന്നു' },
        { year: '2023', text: 'ജപ്പാനെ മറികടന്നു' },
        { year: '2024', text: 'ചൈന ആളോഹരി 8.7 ടൺ' },
      ],
      slides: [
        { kicker: 'കാലാവസ്ഥ', headline: 'ആളോഹരി ബഹിർഗമനത്തിൽ ചൈന ജപ്പാനും ജർമ്മനിക്കും മുന്നിൽ', body: '' },
        { kicker: '2024', headline: 'ശരാശരി ഒരു ചൈനക്കാരൻ', body: '8.7 ടൺ CO₂ പുറന്തള്ളി.', fact_id: 'F2' },
        { kicker: '1990', headline: 'അന്ന് നാലിലൊന്ന്', body: 'ഒരു ചൈനക്കാരന്റെ ശരാശരി ബഹിർഗമനം 2.2 ടൺ.', fact_id: 'F1' },
        { kicker: 'ജപ്പാൻ, 2024', headline: 'ജപ്പാൻ പിന്നിലായി', body: 'ഒരു ജപ്പാൻകാരന്റെ ശരാശരി 7.8 ടൺ.', fact_id: 'F5' },
        { kicker: 'ജർമ്മനി, 2024', headline: 'ജർമ്മനിയും', body: 'ഒരു ജർമ്മൻകാരന്റെ ശരാശരി 6.8 ടൺ.', fact_id: 'F8' },
        { kicker: 'അർഥം', headline: 'അമേരിക്ക ഇപ്പോഴും മുന്നിൽ', body: '2024-ൽ ഒരു അമേരിക്കക്കാരൻ ശരാശരി 14.2 ടൺ പുറന്തള്ളി.' },
      ],
      chart_title: 'ആളോഹരിയിൽ ജപ്പാനെയും ജർമ്മനിയെയും ചൈന മറികടന്നു',
      chart_subtitle: 'ആളോഹരി CO₂ ബഹിർഗമനം, ടൺ, 1990-2024',
      alt_text: '1990-ൽ 2.2 ടണ്ണായിരുന്ന ചൈനയുടെ ആളോഹരി ബഹിർഗമനം 2024-ൽ 8.7 ടണ്ണായി ഉയർന്നു; ജർമ്മനി (6.8), ജപ്പാൻ (7.8) എന്നിവയെ മറികടന്നു.',
      caveat: 'ആളോഹരി കണക്കുകൾ ഓരോ വർഷത്തെയും ജനസംഖ്യാ അനുമാനത്തെ ആശ്രയിക്കുന്നു.',
      facts_used: [],
      glossary: { ചൈന: 'China', ജപ്പാൻ: 'Japan', ജർമ്മനി: 'Germany', അമേരിക്ക: 'United States' },
    },
  },

  // ---------------- S3 rise: Vietnam ----------------
  'rise:Vietnam': {
    en: {
      kicker: 'Fastest riser',
      headline: "Vietnam's CO₂ emissions grew 17.4 times since 1990",
      dek: 'Annual CO₂ emissions, million tonnes, 1990 to 2024',
      body: [
        `Vietnam's carbon dioxide emissions grew faster than those of any other large emitter between 1990 and 2024, according to ${SRC}. The country emitted 21.3 million tonnes in 1990 and 371 million tonnes in 2024, 17.4 times as much.`,
        'In percentage terms that is a rise of 1,642%. The comparison covers the 41 largest emitters.',
        'Next on the list are Qatar, where emissions grew 11.0 times, Bangladesh (7.7 times), India (5.5 times) and Malaysia (5.3 times).',
        "Multiples look large when the starting point is small, and Vietnam's 1990 emissions were low. This data shows how big the change is, not why; the causes need reporting.",
      ],
      big_number: { fact_id: 'F3', value: '17.4 times', caption: "Vietnam's CO₂ emissions in 2024 compared with 1990" },
      key_points: ['21.3 million tonnes in 1990, 371 million tonnes in 2024', '17.4 times as much: the fastest rise among the 41 largest emitters', "India's emissions grew 5.5 times"],
      qa: [
        { q: 'How big is the rise?', a: 'Vietnam emitted 17.4 times as much CO₂ in 2024 as in 1990, a rise of 1,642%.' },
        { q: 'Who else grew fast?', a: 'Qatar (11.0 times), Bangladesh (7.7 times), India (5.5 times) and Malaysia (5.3 times).' },
        { q: 'Why so fast?', a: 'Vietnam started from a low level in 1990. The data shows the size of the change, not the reasons.' },
      ],
      then_now: { then_label: '1990', then_text: 'Vietnam emitted 21.3 million tonnes of CO₂.', now_label: '2024', now_text: 'Vietnam emitted 371 million tonnes, 17.4 times as much.' },
      timeline: [
        { year: '1990', text: 'Vietnam emits 21.3 million tonnes' },
        { year: '2024', text: 'Vietnam emits 371 million tonnes' },
        { year: '2024', text: '17.4 times the 1990 level' },
      ],
      slides: [
        { kicker: 'Fastest riser', headline: "Vietnam's emissions grew 17.4 times", body: '' },
        { kicker: 'In 2024', headline: 'Vietnam emitted', body: 'Up from 21.3 million tonnes in 1990.', fact_id: 'F2' },
        { kicker: 'Since 1990', headline: 'The fastest rise', body: 'Among the 41 largest emitters.', fact_id: 'F3' },
        { kicker: 'In percent', headline: 'A huge jump', body: "Vietnam's emissions rose 1,642% since 1990.", fact_id: 'F4' },
        { kicker: 'India', headline: 'India grew too', body: "India's emissions grew 5.5 times.", fact_id: 'F7' },
        { kicker: 'Keep in mind', headline: 'A low starting point', body: 'Vietnam began small in 1990. The causes of the rise need reporting.' },
      ],
      chart_title: 'Vietnam grew fastest since 1990',
      chart_subtitle: 'CO₂ emissions in 2024 as a multiple of 1990',
      alt_text: "Bar chart: Vietnam's emissions in 2024 were 17.4 times their 1990 level, followed by Qatar (11.0 times), Bangladesh (7.7 times), India (5.5 times) and Malaysia (5.3 times).",
      caveat: 'Multiples look large when the starting point is small.',
      facts_used: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9'],
    },
    ml: {
      kicker: 'അതിവേഗ വളർച്ച',
      headline: 'വിയറ്റ്നാമിന്റെ കാർബൺ ബഹിർഗമനം 1990-നു ശേഷം 17.4 മടങ്ങ്',
      dek: 'വാർഷിക CO₂ ബഹിർഗമനം, 1990 മുതൽ 2024 വരെ',
      body: [
        'വലിയ ബഹിർഗമന രാജ്യങ്ങളിൽ ഏറ്റവും വേഗത്തിൽ കാർബൺ ഡൈ ഓക്സൈഡ് ബഹിർഗമനം വർധിച്ചത് വിയറ്റ്നാമിലാണെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. 1990-ൽ 2.13 കോടി ടൺ ആയിരുന്ന ബഹിർഗമനം 2024-ൽ 37.1 കോടി ടണ്ണായി; 17.4 മടങ്ങ്.',
        'ശതമാനക്കണക്കിൽ ഇത് 1,642 ശതമാനം വർധനയാണ്. ഏറ്റവും വലിയ 41 ബഹിർഗമന രാജ്യങ്ങളെയാണ് താരതമ്യം ചെയ്തത്.',
        'ഖത്തർ (11.0 മടങ്ങ്), ബംഗ്ലാദേശ് (7.7 മടങ്ങ്), ഇന്ത്യ (5.5 മടങ്ങ്), മലേഷ്യ (5.3 മടങ്ങ്) എന്നിവയാണ് തൊട്ടുപിന്നിൽ.',
        'തുടക്കത്തിലെ അളവ് ചെറുതാകുമ്പോൾ മടങ്ങുകണക്ക് വലുതായി തോന്നും; 1990-ൽ വിയറ്റ്നാമിന്റെ ബഹിർഗമനം ചെറുതായിരുന്നു. മാറ്റത്തിന്റെ വലിപ്പമാണ് ഈ ഡാറ്റ കാണിക്കുന്നത്, കാരണങ്ങളല്ല; അതിന് റിപ്പോർട്ടിങ് വേണം.',
      ],
      big_number: { fact_id: 'F3', value: '17.4 മടങ്ങ്', caption: '1990-നെ അപേക്ഷിച്ച് 2024-ലെ വിയറ്റ്നാമിന്റെ CO₂ ബഹിർഗമനം' },
      key_points: ['1990-ൽ 2.13 കോടി ടൺ; 2024-ൽ 37.1 കോടി ടൺ', 'ഏറ്റവും വലിയ 41 രാജ്യങ്ങളിൽ ഏറ്റവും വേഗത്തിലുള്ള വർധന: 17.4 മടങ്ങ്', 'ഇന്ത്യയുടെ ബഹിർഗമനം 5.5 മടങ്ങായി'],
      qa: [
        { q: 'വർധന എത്ര വലുതാണ്?', a: '2024-ൽ വിയറ്റ്നാം 1990-ലേതിന്റെ 17.4 മടങ്ങ് CO₂ പുറന്തള്ളി; 1,642 ശതമാനം വർധന.' },
        { q: 'വേറെ ആരൊക്കെ?', a: 'ഖത്തർ (11.0 മടങ്ങ്), ബംഗ്ലാദേശ് (7.7 മടങ്ങ്), ഇന്ത്യ (5.5 മടങ്ങ്), മലേഷ്യ (5.3 മടങ്ങ്).' },
        { q: 'എന്തുകൊണ്ട് ഇത്ര വേഗം?', a: '1990-ൽ വിയറ്റ്നാമിന്റെ ബഹിർഗമനം ചെറുതായിരുന്നു. മാറ്റത്തിന്റെ കാരണങ്ങൾ ഈ ഡാറ്റയിലില്ല.' },
      ],
      then_now: { then_label: '1990', then_text: 'വിയറ്റ്നാം 2.13 കോടി ടൺ CO₂ പുറന്തള്ളി.', now_label: '2024', now_text: 'വിയറ്റ്നാം 37.1 കോടി ടൺ പുറന്തള്ളി; 17.4 മടങ്ങ്.' },
      timeline: [
        { year: '1990', text: 'വിയറ്റ്നാം: 2.13 കോടി ടൺ' },
        { year: '2024', text: 'വിയറ്റ്നാം: 37.1 കോടി ടൺ' },
        { year: '2024', text: '1990-ലേതിന്റെ 17.4 മടങ്ങ്' },
      ],
      slides: [
        { kicker: 'അതിവേഗ വളർച്ച', headline: 'വിയറ്റ്നാമിന്റെ ബഹിർഗമനം 17.4 മടങ്ങായി', body: '' },
        { kicker: '2024', headline: 'വിയറ്റ്നാമിന്റെ ബഹിർഗമനം', body: '1990-ൽ ഇത് 2.13 കോടി ടൺ മാത്രം.', fact_id: 'F2' },
        { kicker: '1990 മുതൽ', headline: 'ഏറ്റവും വേഗത്തിലുള്ള വർധന', body: 'ഏറ്റവും വലിയ 41 ബഹിർഗമന രാജ്യങ്ങളിൽ.', fact_id: 'F3' },
        { kicker: 'ശതമാനത്തിൽ', headline: 'വൻ കുതിപ്പ്', body: '1990 മുതൽ 1,642 ശതമാനം വർധന.', fact_id: 'F4' },
        { kicker: 'ഇന്ത്യ', headline: 'ഇന്ത്യയും വളർന്നു', body: 'ഇന്ത്യയുടെ ബഹിർഗമനം 5.5 മടങ്ങായി.', fact_id: 'F7' },
        { kicker: 'ശ്രദ്ധിക്കുക', headline: 'ചെറിയ തുടക്കം', body: '1990-ൽ വിയറ്റ്നാമിന്റെ ബഹിർഗമനം ചെറുതായിരുന്നു. കാരണങ്ങൾ റിപ്പോർട്ടിങ്ങിലൂടെ കണ്ടെത്തണം.' },
      ],
      chart_title: '1990 മുതൽ ഏറ്റവും വേഗം വളർന്നത് വിയറ്റ്നാം',
      chart_subtitle: '1990-നെ അപേക്ഷിച്ച് 2024-ലെ ബഹിർഗമനം, മടങ്ങിൽ',
      alt_text: 'ബാർ ചാർട്ട്: 2024-ൽ വിയറ്റ്നാമിന്റെ ബഹിർഗമനം 1990-ലേതിന്റെ 17.4 മടങ്ങ്; തുടർന്ന് ഖത്തർ (11.0 മടങ്ങ്), ബംഗ്ലാദേശ് (7.7 മടങ്ങ്), ഇന്ത്യ (5.5 മടങ്ങ്), മലേഷ്യ (5.3 മടങ്ങ്).',
      caveat: 'തുടക്കത്തിലെ അളവ് ചെറുതാകുമ്പോൾ മടങ്ങുകണക്ക് വലുതായി തോന്നും.',
      facts_used: [],
      glossary: { വിയറ്റ്നാം: 'Vietnam', ഖത്തർ: 'Qatar', ബംഗ്ലാദേശ്: 'Bangladesh', ഇന്ത്യ: 'India', മലേഷ്യ: 'Malaysia' },
    },
  },

  // ---------------- S7 leaders: top five 62% ----------------
  'leaders:China': {
    en: {
      kicker: 'Who emits',
      headline: 'Five countries account for 62% of CO₂ emissions',
      dek: 'Annual CO₂ emissions, million tonnes, 2024',
      body: [
        `Five countries, China, the United States, India, Russia and Japan, produced 62% of the carbon dioxide emitted by the 215 countries and territories in ${SRC} figures for 2024.`,
        'China alone emitted 12,289 million tonnes, more than the United States (4,904 million tonnes) and India (3,193 million tonnes) put together.',
        'Russia emitted 1,781 million tonnes and Japan 962 million tonnes. All 215 countries and territories in the data together emitted 37,398 million tonnes.',
        'The share is calculated from the countries in the data. International shipping and aviation are counted separately, so the share of the full world total is slightly lower.',
      ],
      big_number: { fact_id: 'F1', value: '62%', caption: 'Share of 2024 emissions from the five largest emitters' },
      key_points: ['The five largest: 62% of the total', 'China: 12,289 million tonnes in 2024', 'All 215 in the data: 37,398 million tonnes'],
      qa: [
        { q: 'Who are the five?', a: 'China, the United States, India, Russia and Japan.' },
        { q: "How big is China's part?", a: 'China emitted 12,289 million tonnes of the 37,398 million tonnes in the data.' },
        { q: 'Does this include shipping and flights?', a: 'No. They are counted separately, so the share of the full world total is slightly lower.' },
      ],
      then_now: { then_label: 'The five', then_text: 'China, the United States, India, Russia and Japan: 62% of the total.', now_label: 'Everyone else', now_text: 'All the other countries and territories share the rest.' },
      timeline: [
        { year: '2024', text: 'China: 12,289 million tonnes' },
        { year: '2024', text: 'United States: 4,904 million tonnes' },
        { year: '2024', text: 'India: 3,193 million tonnes' },
      ],
      slides: [
        { kicker: 'Who emits', headline: 'Five countries, most of the CO₂', body: '' },
        { kicker: '2024', headline: 'Five countries', body: 'China, the United States, India, Russia and Japan.', fact_id: 'F1' },
        { kicker: 'China', headline: 'China alone', body: 'emitted this much in 2024.', fact_id: 'F2' },
        { kicker: 'United States', headline: 'The United States', body: 'is a distant second.', fact_id: 'F3' },
        { kicker: 'India', headline: 'India', body: 'is third.', fact_id: 'F4' },
        { kicker: 'Keep in mind', headline: 'Shipping and flights are extra', body: 'They are counted separately, so the true world share is slightly lower.' },
      ],
      chart_title: 'The five largest produce 62% of the total',
      chart_subtitle: 'Annual CO₂ emissions, million tonnes, 2024',
      alt_text: 'Bar chart of the largest emitters in 2024. China leads with 12,289 million tonnes, followed by the United States (4,904) and India (3,193).',
      caveat: 'The share leaves out international shipping and aviation.',
      facts_used: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
    },
    ml: {
      kicker: 'ആരൊക്കെ',
      headline: 'അഞ്ച് രാജ്യങ്ങൾ ചേർന്ന് 62 ശതമാനം കാർബൺ ബഹിർഗമനം',
      dek: 'വാർഷിക CO₂ ബഹിർഗമനം, 2024',
      body: [
        'ചൈന, അമേരിക്ക, ഇന്ത്യ, റഷ്യ, ജപ്പാൻ എന്നീ അഞ്ച് രാജ്യങ്ങൾ ചേർന്നാണ് 2024-ലെ ആകെ കാർബൺ ഡൈ ഓക്സൈഡ് ബഹിർഗമനത്തിന്റെ 62 ശതമാനവും പുറന്തള്ളിയതെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. ഡാറ്റയിലെ 215 രാജ്യങ്ങളുടെയും പ്രദേശങ്ങളുടെയും കണക്കാണിത്.',
        'ചൈന മാത്രം 1,229 കോടി ടൺ പുറന്തള്ളി. അമേരിക്ക 490 കോടി ടണ്ണും ഇന്ത്യ 319 കോടി ടണ്ണും.',
        'റഷ്യ 178 കോടി ടൺ, ജപ്പാൻ 96.2 കോടി ടൺ. ഡാറ്റയിലെ 215 രാജ്യങ്ങളുടെയും പ്രദേശങ്ങളുടെയും ആകെ ബഹിർഗമനം 3,740 കോടി ടൺ.',
        'രാജ്യാന്തര കപ്പൽ, വിമാന ഗതാഗതത്തിൽ നിന്നുള്ള ബഹിർഗമനം ഈ കണക്കിൽ ഇല്ല. അവ കൂടി ചേർത്താൽ ലോകത്തെ ആകെ ബഹിർഗമനത്തിൽ ഈ അഞ്ച് രാജ്യങ്ങളുടെ പങ്ക് അല്പം കുറയും.',
      ],
      big_number: { fact_id: 'F1', value: '62 ശതമാനം', caption: '2024-ലെ ബഹിർഗമനത്തിൽ ഏറ്റവും വലിയ അഞ്ച് രാജ്യങ്ങളുടെ പങ്ക്' },
      key_points: ['ഏറ്റവും വലിയ അഞ്ച് രാജ്യങ്ങൾ: ആകെയുടെ 62 ശതമാനം', 'ചൈന: 2024-ൽ 1,229 കോടി ടൺ', 'ഡാറ്റയിലെ 215 രാജ്യങ്ങളും പ്രദേശങ്ങളും: 3,740 കോടി ടൺ'],
      qa: [
        { q: 'ഏതൊക്കെയാണ് ആ അഞ്ച് രാജ്യങ്ങൾ?', a: 'ചൈന, അമേരിക്ക, ഇന്ത്യ, റഷ്യ, ജപ്പാൻ.' },
        { q: 'ചൈനയുടെ പങ്ക് എത്ര?', a: 'ഡാറ്റയിലെ ആകെ 3,740 കോടി ടണ്ണിൽ 1,229 കോടി ടൺ ചൈനയുടേതാണ്.' },
        { q: 'കപ്പലും വിമാനവും ഉൾപ്പെടുമോ?', a: 'ഇല്ല. അവ വേറെയാണ് കണക്കാക്കുന്നത്; അതിനാൽ ലോകത്തെ ആകെ ബഹിർഗമനത്തിലെ പങ്ക് അല്പം കുറവായിരിക്കും.' },
      ],
      then_now: { then_label: 'അഞ്ച് രാജ്യങ്ങൾ', then_text: 'ചൈന, അമേരിക്ക, ഇന്ത്യ, റഷ്യ, ജപ്പാൻ: ആകെയുടെ 62 ശതമാനം.', now_label: 'മറ്റുള്ളവർ', now_text: 'ബാക്കി രാജ്യങ്ങളും പ്രദേശങ്ങളും ചേർന്ന് ശേഷിക്കുന്ന പങ്ക്.' },
      timeline: [
        { year: '2024', text: 'ചൈന: 1,229 കോടി ടൺ' },
        { year: '2024', text: 'അമേരിക്ക: 490 കോടി ടൺ' },
        { year: '2024', text: 'ഇന്ത്യ: 319 കോടി ടൺ' },
      ],
      slides: [
        { kicker: 'ആരൊക്കെ', headline: 'അഞ്ച് രാജ്യങ്ങൾ, ബഹിർഗമനത്തിന്റെ ഭൂരിഭാഗം', body: '' },
        { kicker: '2024', headline: 'അഞ്ച് രാജ്യങ്ങൾ', body: 'ചൈന, അമേരിക്ക, ഇന്ത്യ, റഷ്യ, ജപ്പാൻ.', fact_id: 'F1' },
        { kicker: 'ചൈന', headline: 'ചൈന മാത്രം', body: '2024-ൽ ഇത്രയും പുറന്തള്ളി.', fact_id: 'F2' },
        { kicker: 'അമേരിക്ക', headline: 'അമേരിക്ക', body: 'ഏറെ പിന്നിൽ രണ്ടാമത്.', fact_id: 'F3' },
        { kicker: 'ഇന്ത്യ', headline: 'ഇന്ത്യ', body: 'മൂന്നാമത്.', fact_id: 'F4' },
        { kicker: 'ശ്രദ്ധിക്കുക', headline: 'കപ്പലും വിമാനവും പുറത്ത്', body: 'അവ വേറെയാണ് കണക്കാക്കുന്നത്; ലോകത്തെ ആകെ പങ്ക് അല്പം കുറവായിരിക്കും.' },
      ],
      chart_title: 'ഏറ്റവും വലിയ അഞ്ച് രാജ്യങ്ങൾ: ആകെയുടെ 62 ശതമാനം',
      chart_subtitle: 'വാർഷിക CO₂ ബഹിർഗമനം, 2024',
      alt_text: '2024-ലെ ഏറ്റവും വലിയ ബഹിർഗമന രാജ്യങ്ങളുടെ ബാർ ചാർട്ട്. ചൈന 1,229 കോടി ടൺ; തുടർന്ന് അമേരിക്ക (490 കോടി), ഇന്ത്യ (319 കോടി).',
      caveat: 'രാജ്യാന്തര കപ്പൽ, വിമാന ഗതാഗതം ഈ കണക്കിൽ ഇല്ല.',
      facts_used: [],
      glossary: { ചൈന: 'China', അമേരിക്ക: 'United States', ഇന്ത്യ: 'India', റഷ്യ: 'Russia', ജപ്പാൻ: 'Japan' },
    },
  },

  // ---------------- S2 imports: UK ----------------
  'imports:United_Kingdom': {
    en: {
      kicker: 'Hidden in the data',
      headline: "Counting imports, the UK's emissions fell 27%, not 49%",
      dek: 'Change in CO₂ emissions, made at home vs counting imports, 1990 to 2023',
      body: [
        `Britain's carbon dioxide emissions from inside its borders fell 49% between 1990 and 2023, according to ${SRC}. But counting the emissions released abroad to make the goods Britain imports, the fall is 27%.`,
        'In 2023 the UK produced 308 million tonnes at home, while its emissions counting imports came to 487 million tonnes.',
        'France shows the same pattern: down 32% at home, down 16% counting imports. In the United States, emissions fell 4.2% at home but rose 7.5% once imports are counted.',
        'Figures that count imports are estimates built from trade data and end in 2023. The gap suggests part of the fall at home is linked to production moving abroad.',
      ],
      big_number: { fact_id: 'F2', value: '27%', caption: 'Fall in UK emissions since 1990, counting imports' },
      key_points: ['Made at home: down 49% since 1990', 'Counting imports: down 27%', 'In the US: down 4.2% at home, up 7.5% counting imports'],
      qa: [
        { q: 'What does "counting imports" mean?', a: 'It adds the CO₂ released in other countries to make the things Britain buys, and takes off what Britain makes for export.' },
        { q: 'So did the UK really cut emissions?', a: 'Yes, but less than the usual figure suggests: 27% counting imports, against 49% at home.' },
        { q: 'Is this only the UK?', a: 'No. France fell 32% at home but 16% counting imports.' },
      ],
      then_now: { then_label: 'At home', then_text: 'UK emissions made inside the country fell 49% between 1990 and 2023.', now_label: 'Counting imports', now_text: 'The fall shrinks to 27%.' },
      timeline: [
        { year: '1990', text: 'The starting point for both measures' },
        { year: '2023', text: 'Made at home: down 49%' },
        { year: '2023', text: 'Counting imports: down 27%' },
      ],
      slides: [
        { kicker: 'Hidden in the data', headline: "The UK's cut is smaller than it looks", body: '' },
        { kicker: 'Made at home', headline: 'The usual number', body: 'UK emissions made inside the country fell 49% since 1990.', fact_id: 'F1' },
        { kicker: 'Counting imports', headline: 'The fuller picture', body: 'Counting the CO₂ in what Britain imports, the fall is 27%.', fact_id: 'F2' },
        { kicker: '2023', headline: 'What Britain consumes', body: 'Emissions counting imports, against 308 million tonnes made at home.', fact_id: 'F12' },
        { kicker: 'United States', headline: 'In the US, the cut disappears', body: 'Down 4.2% at home, up 7.5% counting imports.', fact_id: 'F17' },
        { kicker: 'Keep in mind', headline: 'Estimates from trade data', body: 'Figures that count imports are modelled and end in 2023.' },
      ],
      chart_title: 'Counting imports shrinks the fall',
      chart_subtitle: 'Change in CO₂ emissions, 1990 to 2023, %',
      alt_text: 'Bar chart: the UK fell 49% at home but 27% counting imports; France fell 32% and 16%.',
      caveat: 'Figures that count imports are estimates and end in 2023.',
      facts_used: ['F1', 'F2', 'F5', 'F6', 'F11', 'F12', 'F16', 'F17'],
    },
    ml: {
      kicker: 'ഡാറ്റയിലെ രഹസ്യം',
      headline: 'ഇറക്കുമതി കൂടി കണക്കാക്കിയാൽ ബ്രിട്ടന്റെ ബഹിർഗമനം കുറഞ്ഞത് 27 ശതമാനം',
      dek: 'CO₂ ബഹിർഗമനത്തിലെ മാറ്റം: രാജ്യത്തിനകത്തും ഇറക്കുമതി ഉൾപ്പെടെയും, 1990 മുതൽ 2023 വരെ',
      body: [
        '1990 മുതൽ 2023 വരെ ബ്രിട്ടന്റെ അതിർത്തിക്കുള്ളിലെ കാർബൺ ഡൈ ഓക്സൈഡ് ബഹിർഗമനം 49 ശതമാനം കുറഞ്ഞുവെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. എന്നാൽ ബ്രിട്ടൻ ഇറക്കുമതി ചെയ്യുന്ന സാധനങ്ങൾ മറ്റു രാജ്യങ്ങളിൽ ഉണ്ടാക്കുമ്പോഴുള്ള ബഹിർഗമനം കൂടി കണക്കാക്കിയാൽ കുറവ് 27 ശതമാനം മാത്രം.',
        '2023-ൽ ബ്രിട്ടനിൽ ഉൽപാദിപ്പിച്ച ബഹിർഗമനം 30.8 കോടി ടൺ; ഇറക്കുമതി ഉൾപ്പെടെയുള്ള ബഹിർഗമനം 48.7 കോടി ടൺ.',
        'ഫ്രാൻസിലും ഇതേ പ്രവണത: രാജ്യത്തിനകത്ത് 32 ശതമാനം കുറഞ്ഞു, ഇറക്കുമതി ഉൾപ്പെടുത്തിയാൽ 16 ശതമാനം മാത്രം കുറവ്. അമേരിക്കയിൽ രാജ്യത്തിനകത്തെ ബഹിർഗമനം 4.2 ശതമാനം കുറഞ്ഞെങ്കിലും, ഇറക്കുമതി ചേർത്താൽ 7.5 ശതമാനം വർധിച്ചു.',
        'ഇറക്കുമതി ഉൾപ്പെടുത്തിയ കണക്കുകൾ വ്യാപാര ഡാറ്റയിൽ നിന്നുള്ള അനുമാനങ്ങളാണ്; 2023 വരെ മാത്രമേ ലഭ്യമുള്ളൂ. രാജ്യത്തിനകത്തെ കുറവിന്റെ ഒരു ഭാഗം ഉൽപാദനം വിദേശത്തേക്ക് മാറിയതുമായി ബന്ധപ്പെട്ടിരിക്കുന്നുവെന്നാണ് ഈ വ്യത്യാസം സൂചിപ്പിക്കുന്നത്.',
      ],
      big_number: { fact_id: 'F2', value: '27 ശതമാനം', caption: 'ഇറക്കുമതി ഉൾപ്പെടെ, 1990 മുതൽ ബ്രിട്ടന്റെ ബഹിർഗമനത്തിലെ കുറവ്' },
      key_points: ['രാജ്യത്തിനകത്ത്: 49 ശതമാനം കുറഞ്ഞു', 'ഇറക്കുമതി ഉൾപ്പെടെ: 27 ശതമാനം മാത്രം കുറവ്', 'അമേരിക്കയിൽ: അകത്ത് 4.2 ശതമാനം കുറവ്, ഇറക്കുമതി ചേർത്താൽ 7.5 ശതമാനം വർധന'],
      qa: [
        { q: '"ഇറക്കുമതി കൂടി കണക്കാക്കുക" എന്നാൽ?', a: 'ബ്രിട്ടൻ വാങ്ങുന്ന സാധനങ്ങൾ മറ്റു രാജ്യങ്ങളിൽ ഉണ്ടാക്കുമ്പോഴുള്ള ബഹിർഗമനം കൂട്ടിച്ചേർക്കുകയും കയറ്റുമതിക്കായി ഉണ്ടാക്കുന്നതിന്റേത് കുറയ്ക്കുകയും ചെയ്യുന്നു.' },
        { q: 'അപ്പോൾ ബ്രിട്ടൻ ബഹിർഗമനം കുറച്ചില്ലേ?', a: 'കുറച്ചു; പക്ഷേ സാധാരണ പറയുന്നത്ര ഇല്ല: രാജ്യത്തിനകത്ത് 49 ശതമാനം കുറവ്, ഇറക്കുമതി ഉൾപ്പെടെ 27 ശതമാനം മാത്രം കുറവ്.' },
        { q: 'ബ്രിട്ടനിൽ മാത്രമാണോ?', a: 'അല്ല. ഫ്രാൻസിൽ രാജ്യത്തിനകത്ത് 32 ശതമാനം കുറഞ്ഞു; ഇറക്കുമതി ഉൾപ്പെടെ 16 ശതമാനം മാത്രം കുറവ്.' },
      ],
      then_now: { then_label: 'രാജ്യത്തിനകത്ത്', then_text: '1990 മുതൽ 2023 വരെ 49 ശതമാനം കുറഞ്ഞു.', now_label: 'ഇറക്കുമതി ഉൾപ്പെടെ', now_text: 'കുറവ് 27 ശതമാനം മാത്രം.' },
      timeline: [
        { year: '1990', text: 'രണ്ടു കണക്കുകളുടെയും തുടക്കം' },
        { year: '2023', text: 'രാജ്യത്തിനകത്ത്: 49 ശതമാനം കുറവ്' },
        { year: '2023', text: 'ഇറക്കുമതി ഉൾപ്പെടെ: 27 ശതമാനം കുറവ്' },
      ],
      slides: [
        { kicker: 'ഡാറ്റയിലെ രഹസ്യം', headline: 'ബ്രിട്ടന്റെ നേട്ടം തോന്നുന്നത്ര വലുതല്ല', body: '' },
        { kicker: 'രാജ്യത്തിനകത്ത്', headline: 'സാധാരണ പറയുന്ന കണക്ക്', body: '1990 മുതൽ 49 ശതമാനം കുറവ്.', fact_id: 'F1' },
        { kicker: 'ഇറക്കുമതി ഉൾപ്പെടെ', headline: 'മുഴുവൻ ചിത്രം', body: 'ഇറക്കുമതി കൂടി കണക്കാക്കിയാൽ കുറവ് 27 ശതമാനം.', fact_id: 'F2' },
        { kicker: '2023', headline: 'ബ്രിട്ടൻ ഉപയോഗിക്കുന്നത്', body: 'ഇറക്കുമതി ഉൾപ്പെടെയുള്ള ബഹിർഗമനം; രാജ്യത്തിനകത്ത് 30.8 കോടി ടൺ.', fact_id: 'F12' },
        { kicker: 'അമേരിക്ക', headline: 'അമേരിക്കയിൽ കുറവ് ഇല്ലാതാകുന്നു', body: 'അകത്ത് 4.2 ശതമാനം കുറവ്; ഇറക്കുമതി ചേർത്താൽ 7.5 ശതമാനം വർധന.', fact_id: 'F17' },
        { kicker: 'ശ്രദ്ധിക്കുക', headline: 'വ്യാപാര ഡാറ്റയിൽ നിന്നുള്ള അനുമാനം', body: 'ഇറക്കുമതി ഉൾപ്പെടുത്തിയ കണക്കുകൾ 2023 വരെ മാത്രം.' },
      ],
      chart_title: 'ഇറക്കുമതി കൂടി കണക്കാക്കിയാൽ കുറവ് ചുരുങ്ങുന്നു',
      chart_subtitle: 'CO₂ ബഹിർഗമനത്തിലെ മാറ്റം, 1990 മുതൽ 2023 വരെ, ശതമാനത്തിൽ',
      alt_text: 'ബാർ ചാർട്ട്: ബ്രിട്ടനിൽ രാജ്യത്തിനകത്ത് 49 ശതമാനം കുറവ്, ഇറക്കുമതി ഉൾപ്പെടെ 27 ശതമാനം; ഫ്രാൻസിൽ 32 ശതമാനം, 16 ശതമാനം.',
      caveat: 'ഇറക്കുമതി ഉൾപ്പെടുത്തിയ കണക്കുകൾ അനുമാനങ്ങളാണ്; 2023 വരെ മാത്രം.',
      facts_used: [],
      glossary: { ബ്രിട്ടൻ: 'United Kingdom', ഫ്രാൻസ്: 'France', അമേരിക്ക: 'United States' },
    },
  },

  // ---------------- S9 total vs per person: India ----------------
  'total-vs-per-person:India': {
    en: {
      kicker: 'Hidden in the data',
      headline: 'India is the 3rd biggest emitter, but low per person',
      dek: 'Annual CO₂ emissions, total and per person, 2024',
      body: [
        `India emitted 3,193 million tonnes of carbon dioxide in 2024, the third-largest total of any country, according to ${SRC}.`,
        'Per person, the picture flips. The average person in India emitted 2.2 tonnes, less than half the average of 4.6 tonnes across the countries in the data: 48% of it.',
        'Saudi Arabia, at 20.4 tonnes per person, emits 9.3 times as much per person as India.',
        'The average here is calculated from the countries in this data, weighted by population. It is not an official world figure.',
      ],
      big_number: { fact_id: 'F3', value: '2.2 tonnes', caption: 'CO₂ per person in India, 2024' },
      key_points: ['3rd largest total: 3,193 million tonnes in 2024', 'Per person: 2.2 tonnes', 'The average across the data: 4.6 tonnes per person'],
      qa: [
        { q: 'Is India a big emitter?', a: 'In total, yes: 3,193 million tonnes in 2024, the third-largest.' },
        { q: 'And per person?', a: 'Low: 2.2 tonnes, 48% of the average of 4.6 tonnes.' },
        { q: 'Who emits the most per person among big emitters?', a: 'Saudi Arabia, at 20.4 tonnes per person, 9.3 times India.' },
      ],
      then_now: { then_label: 'In total', then_text: '3rd largest emitter: 3,193 million tonnes.', now_label: 'Per person', now_text: '2.2 tonnes, 48% of the average.' },
      timeline: [
        { year: '2024', text: 'Total: 3,193 million tonnes' },
        { year: '2024', text: 'Per person: 2.2 tonnes' },
        { year: '2024', text: 'Average across the data: 4.6 tonnes' },
      ],
      slides: [
        { kicker: 'Hidden in the data', headline: 'Big in total, small per person', body: '' },
        { kicker: 'In total', headline: 'India ranks third', body: 'among all emitters in 2024.', fact_id: 'F1' },
        { kicker: 'India, 2024', headline: 'Total emissions', body: 'Only China and the US emit more in total.', fact_id: 'F2' },
        { kicker: 'Per person', headline: 'The average person in India', body: 'emitted this much CO₂ in 2024.', fact_id: 'F3' },
        { kicker: 'The average', headline: 'Across the data', body: 'India is at 48% of this average.', fact_id: 'F4' },
        { kicker: 'Keep in mind', headline: 'Not an official world figure', body: 'The average is calculated from the countries in this data.' },
      ],
      chart_title: 'Big total, small per person: India',
      chart_subtitle: 'CO₂ emissions per person, tonnes, 2024, the 10 largest emitters',
      alt_text: 'Bar chart of emissions per person for the largest emitters in 2024. Saudi Arabia is highest at 20.4 tonnes; India is lowest at 2.2 tonnes.',
      caveat: 'The average covers the countries in this data, not an official world figure.',
      facts_used: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7'],
    },
    ml: {
      kicker: 'ഡാറ്റയിലെ രഹസ്യം',
      headline: 'ആകെ ബഹിർഗമനത്തിൽ ഇന്ത്യ മൂന്നാമത്; ആളോഹരിയിൽ ഏറെ പിന്നിൽ',
      dek: 'വാർഷിക CO₂ ബഹിർഗമനം, ആകെയും ആളോഹരിയും, 2024',
      body: [
        '2024-ൽ ഇന്ത്യ 319 കോടി ടൺ കാർബൺ ഡൈ ഓക്സൈഡ് പുറന്തള്ളിയെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. ആകെ ബഹിർഗമനത്തിൽ ലോകത്ത് മൂന്നാം സ്ഥാനം.',
        'എന്നാൽ ആളോഹരി കണക്കിൽ ചിത്രം മാറുന്നു. ശരാശരി ഒരു ഇന്ത്യക്കാരന്റെ ബഹിർഗമനം 2.2 ടൺ മാത്രം; ഡാറ്റയിലെ രാജ്യങ്ങളുടെ ശരാശരിയായ 4.6 ടണ്ണിന്റെ പകുതിയിൽ താഴെ, 48 ശതമാനം.',
        'സൗദി അറേബ്യയിൽ ആളോഹരി ബഹിർഗമനം 20.4 ടൺ; ഇന്ത്യയുടേതിന്റെ 9.3 മടങ്ങ്.',
        'ഈ ശരാശരി ഡാറ്റയിലെ രാജ്യങ്ങളുടെ ജനസംഖ്യ കണക്കിലെടുത്ത് കണ്ടെത്തിയതാണ്; ഔദ്യോഗിക ലോക കണക്കല്ല.',
      ],
      big_number: { fact_id: 'F3', value: '2.2 ടൺ', caption: '2024-ൽ ഒരു ഇന്ത്യക്കാരന്റെ ശരാശരി CO₂ ബഹിർഗമനം' },
      key_points: ['ആകെ ബഹിർഗമനത്തിൽ മൂന്നാം സ്ഥാനം: 319 കോടി ടൺ', 'ആളോഹരി: 2.2 ടൺ മാത്രം', 'ഡാറ്റയിലെ ശരാശരി: ആളോഹരി 4.6 ടൺ'],
      qa: [
        { q: 'ഇന്ത്യ വലിയ ബഹിർഗമന രാജ്യമാണോ?', a: 'ആകെ കണക്കിൽ അതെ: 2024-ൽ 319 കോടി ടൺ, മൂന്നാം സ്ഥാനം.' },
        { q: 'ആളോഹരിയിലോ?', a: 'വളരെ കുറവ്: 2.2 ടൺ, ശരാശരിയായ 4.6 ടണ്ണിന്റെ 48 ശതമാനം.' },
        { q: 'വലിയ രാജ്യങ്ങളിൽ ആളോഹരി ഏറ്റവും കൂടുതൽ ആർക്ക്?', a: 'സൗദി അറേബ്യ: ആളോഹരി 20.4 ടൺ, ഇന്ത്യയുടെ 9.3 മടങ്ങ്.' },
      ],
      then_now: { then_label: 'ആകെ', then_text: 'മൂന്നാം സ്ഥാനം: 319 കോടി ടൺ.', now_label: 'ആളോഹരി', now_text: '2.2 ടൺ; ശരാശരിയുടെ 48 ശതമാനം.' },
      timeline: [
        { year: '2024', text: 'ആകെ: 319 കോടി ടൺ' },
        { year: '2024', text: 'ആളോഹരി: 2.2 ടൺ' },
        { year: '2024', text: 'ഡാറ്റയിലെ ശരാശരി: 4.6 ടൺ' },
      ],
      slides: [
        { kicker: 'ഡാറ്റയിലെ രഹസ്യം', headline: 'ആകെയിൽ മുന്നിൽ, ആളോഹരിയിൽ പിന്നിൽ', body: '' },
        { kicker: 'ആകെ', headline: 'ഇന്ത്യ മൂന്നാം സ്ഥാനത്ത്', body: '2024-ലെ ആകെ ബഹിർഗമനത്തിൽ.', fact_id: 'F1' },
        { kicker: 'ഇന്ത്യ, 2024', headline: 'ആകെ ബഹിർഗമനം', body: 'ചൈനയും അമേരിക്കയും മാത്രം മുന്നിൽ.', fact_id: 'F2' },
        { kicker: 'ആളോഹരി', headline: 'ശരാശരി ഒരു ഇന്ത്യക്കാരൻ', body: '2024-ൽ ഇത്രയും CO₂ പുറന്തള്ളി.', fact_id: 'F3' },
        { kicker: 'ശരാശരി', headline: 'ഡാറ്റയിലെ രാജ്യങ്ങളുടെ ശരാശരി', body: 'ഇന്ത്യ ഇതിന്റെ 48 ശതമാനം മാത്രം.', fact_id: 'F4' },
        { kicker: 'ശ്രദ്ധിക്കുക', headline: 'ഔദ്യോഗിക ലോക കണക്കല്ല', body: 'ഡാറ്റയിലെ രാജ്യങ്ങളിൽ നിന്ന് കണ്ടെത്തിയ ശരാശരി.' },
      ],
      chart_title: 'ആകെയിൽ വലുത്, ആളോഹരിയിൽ ചെറുത്: ഇന്ത്യ',
      chart_subtitle: 'ആളോഹരി CO₂ ബഹിർഗമനം, ടൺ, 2024, ഏറ്റവും വലിയ രാജ്യങ്ങൾ',
      alt_text: 'വലിയ ബഹിർഗമന രാജ്യങ്ങളുടെ 2024-ലെ ആളോഹരി ബഹിർഗമനത്തിന്റെ ബാർ ചാർട്ട്. സൗദി അറേബ്യ 20.4 ടൺ; ഇന്ത്യ 2.2 ടൺ.',
      caveat: 'ഈ ശരാശരി ഡാറ്റയിലെ രാജ്യങ്ങളുടേതാണ്; ഔദ്യോഗിക ലോക കണക്കല്ല.',
      facts_used: [],
      glossary: { ഇന്ത്യ: 'India', ചൈന: 'China', അമേരിക്ക: 'United States', 'സൗദി അറേബ്യ': 'Saudi Arabia' },
    },
  },

  // ---------------- S5 climbers: Indonesia ----------------
  'climbers:Indonesia': {
    en: {
      kicker: 'Hidden in the data',
      headline: 'Indonesia climbed from 25th to 6th biggest emitter',
      dek: 'Rank by annual CO₂ emissions, 1990 and 2024',
      body: [
        `Indonesia has climbed from 25th to 6th place among the world's carbon dioxide emitters since 1990, according to ${SRC}. Its emissions grew from 155 million tonnes in 1990 to 812 million tonnes in 2024.`,
        'Iran rose from 20th to 7th, Saudi Arabia from 21st to 8th and South Korea from 17th to 9th. Turkey moved from 26th to 12th.',
        'These climbs are easy to miss: percentage rankings favour countries that started small, while the steady rise of mid-sized economies only shows when the totals are ranked in both years.',
        'A rank can also rise because others fall, so the totals matter as well as the ranks.',
      ],
      big_number: { fact_id: 'F2', value: '6th', caption: "Indonesia's rank by CO₂ emissions in 2024, up from 25th" },
      key_points: ['Indonesia: 25th in 1990, 6th in 2024', 'Emissions: 155 million tonnes to 812 million tonnes', 'Iran: 20th to 7th'],
      qa: [
        { q: 'How far did Indonesia climb?', a: 'From 25th in 1990 to 6th in 2024.' },
        { q: 'How much more does it emit?', a: 'Its emissions grew from 155 million tonnes to 812 million tonnes.' },
        { q: 'Who else climbed?', a: 'Iran (20th to 7th), Saudi Arabia (21st to 8th), South Korea (17th to 9th) and Turkey (26th to 12th).' },
      ],
      then_now: { then_label: '1990', then_text: 'Indonesia ranked 25th, with 155 million tonnes.', now_label: '2024', now_text: 'Indonesia ranks 6th, with 812 million tonnes.' },
      timeline: [
        { year: '1990', text: 'Indonesia ranks 25th' },
        { year: '2024', text: 'Indonesia ranks 6th' },
        { year: '2024', text: 'Iran ranks 7th, up from 20th' },
      ],
      slides: [
        { kicker: 'Hidden in the data', headline: 'The climber nobody talks about', body: '' },
        { kicker: 'Indonesia, 2024', headline: 'Now 6th', body: 'Up from 25th in 1990.', fact_id: 'F2' },
        { kicker: 'Indonesia, 2024', headline: 'Its emissions', body: 'Up from 155 million tonnes in 1990.', fact_id: 'F4' },
        { kicker: 'Iran, 2024', headline: 'Iran climbed too', body: 'Up from 20th in 1990.', fact_id: 'F10' },
        { kicker: 'Saudi Arabia, 2024', headline: 'And Saudi Arabia', body: 'Up from 21st in 1990.', fact_id: 'F14' },
        { kicker: 'Keep in mind', headline: 'Ranks move when others fall', body: 'Look at the totals as well as the ranks.' },
      ],
      chart_title: 'Indonesia climbed the table',
      chart_subtitle: 'Rank by total CO₂ emissions, 1990 and 2024 (1 = largest)',
      alt_text: 'Slope chart of ranks: Indonesia moved from 25th to 6th, Iran from 20th to 7th, Saudi Arabia from 21st to 8th.',
      caveat: 'Ranks can rise because others fall; check the totals too.',
      facts_used: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F9', 'F10', 'F13', 'F14', 'F17', 'F18'],
    },
    ml: {
      kicker: 'ഡാറ്റയിലെ രഹസ്യം',
      headline: 'ബഹിർഗമനത്തിൽ ഇന്തോനേഷ്യ 25-ാം സ്ഥാനത്തുനിന്ന് ആറാം സ്ഥാനത്തേക്ക്',
      dek: 'വാർഷിക CO₂ ബഹിർഗമനത്തിലെ സ്ഥാനം, 1990-ലും 2024-ലും',
      body: [
        '1990-നു ശേഷം കാർബൺ ഡൈ ഓക്സൈഡ് ബഹിർഗമന രാജ്യങ്ങളുടെ പട്ടികയിൽ ഇന്തോനേഷ്യ 25-ാം സ്ഥാനത്തുനിന്ന് ആറാം സ്ഥാനത്തേക്ക് ഉയർന്നുവെന്ന് ഗ്ലോബൽ കാർബൺ ബജറ്റിന്റെ കണക്കുകൾ. 1990-ൽ 15.5 കോടി ടൺ ആയിരുന്ന ബഹിർഗമനം 2024-ൽ 81.2 കോടി ടണ്ണായി.',
        'ഇറാൻ 20-ാം സ്ഥാനത്തുനിന്ന് ഏഴാം സ്ഥാനത്തേക്കും സൗദി അറേബ്യ 21-ാം സ്ഥാനത്തുനിന്ന് എട്ടാം സ്ഥാനത്തേക്കും ദക്ഷിണ കൊറിയ 17-ാം സ്ഥാനത്തുനിന്ന് ഒൻപതാം സ്ഥാനത്തേക്കും ഉയർന്നു. തുർക്കി 26-ാം സ്ഥാനത്തുനിന്ന് 12-ാം സ്ഥാനത്തെത്തി.',
        'ശതമാനക്കണക്കിലുള്ള പട്ടികകൾ ചെറിയ തുടക്കമുള്ള രാജ്യങ്ങളെയാണ് മുന്നിൽ കാണിക്കുക. ഇടത്തരം സമ്പദ്‌വ്യവസ്ഥകളുടെ ഈ സ്ഥിരമായ കയറ്റം രണ്ടു വർഷത്തെയും ആകെ കണക്കുകൾ നിരത്തുമ്പോൾ മാത്രമേ കാണാനാകൂ.',
        'മറ്റുള്ളവർ താഴോട്ടു പോകുമ്പോഴും സ്ഥാനം ഉയരാം; അതിനാൽ സ്ഥാനത്തിനൊപ്പം ആകെ കണക്കും നോക്കണം.',
      ],
      big_number: { fact_id: 'F2', value: 'ആറാം', caption: '2024-ൽ ബഹിർഗമനത്തിൽ ഇന്തോനേഷ്യയുടെ സ്ഥാനം; 1990-ൽ 25-ാം സ്ഥാനം' },
      key_points: ['ഇന്തോനേഷ്യ: 1990-ൽ 25-ാം സ്ഥാനം, 2024-ൽ ആറാം സ്ഥാനം', 'ബഹിർഗമനം: 15.5 കോടി ടണ്ണിൽ നിന്ന് 81.2 കോടി ടണ്ണിലേക്ക്', 'ഇറാൻ: 20-ാം സ്ഥാനത്തുനിന്ന് ഏഴാം സ്ഥാനത്തേക്ക്'],
      qa: [
        { q: 'ഇന്തോനേഷ്യ എത്ര ഉയർന്നു?', a: '1990-ലെ 25-ാം സ്ഥാനത്തുനിന്ന് 2024-ൽ ആറാം സ്ഥാനത്തേക്ക്.' },
        { q: 'ബഹിർഗമനം എത്ര കൂടി?', a: '15.5 കോടി ടണ്ണിൽ നിന്ന് 81.2 കോടി ടണ്ണായി.' },
        { q: 'വേറെ ആരൊക്കെ ഉയർന്നു?', a: 'ഇറാൻ (20-ാം സ്ഥാനത്തുനിന്ന് ഏഴാം സ്ഥാനത്തേക്ക്), സൗദി അറേബ്യ (21-ാം സ്ഥാനത്തുനിന്ന് എട്ടാം സ്ഥാനത്തേക്ക്), തുർക്കി (26-ാം സ്ഥാനത്തുനിന്ന് 12-ാം സ്ഥാനത്തേക്ക്).' },
      ],
      then_now: { then_label: '1990', then_text: 'ഇന്തോനേഷ്യ 25-ാം സ്ഥാനത്ത്; 15.5 കോടി ടൺ.', now_label: '2024', now_text: 'ഇന്തോനേഷ്യ ആറാം സ്ഥാനത്ത്; 81.2 കോടി ടൺ.' },
      timeline: [
        { year: '1990', text: 'ഇന്തോനേഷ്യ 25-ാം സ്ഥാനത്ത്' },
        { year: '2024', text: 'ഇന്തോനേഷ്യ ആറാം സ്ഥാനത്ത്' },
        { year: '2024', text: 'ഇറാൻ ഏഴാം സ്ഥാനത്ത്; 1990-ൽ 20-ാം സ്ഥാനം' },
      ],
      slides: [
        { kicker: 'ഡാറ്റയിലെ രഹസ്യം', headline: 'ആരും ശ്രദ്ധിക്കാത്ത കയറ്റം', body: '' },
        { kicker: 'ഇന്തോനേഷ്യ, 2024', headline: 'ഇപ്പോൾ ആറാം സ്ഥാനം', body: '1990-ൽ 25-ാം സ്ഥാനത്തായിരുന്നു.', fact_id: 'F2' },
        { kicker: 'ഇന്തോനേഷ്യ, 2024', headline: 'ബഹിർഗമനം', body: '1990-ൽ 15.5 കോടി ടൺ മാത്രം.', fact_id: 'F4' },
        { kicker: 'ഇറാൻ, 2024', headline: 'ഇറാനും ഉയർന്നു', body: '1990-ൽ 20-ാം സ്ഥാനത്തായിരുന്നു.', fact_id: 'F10' },
        { kicker: 'സൗദി അറേബ്യ, 2024', headline: 'സൗദി അറേബ്യയും', body: '1990-ൽ 21-ാം സ്ഥാനത്തായിരുന്നു.', fact_id: 'F14' },
        { kicker: 'ശ്രദ്ധിക്കുക', headline: 'മറ്റുള്ളവർ താഴുമ്പോഴും സ്ഥാനം ഉയരാം', body: 'സ്ഥാനത്തിനൊപ്പം ആകെ കണക്കും നോക്കുക.' },
      ],
      chart_title: 'പട്ടികയിൽ ഇന്തോനേഷ്യയുടെ കയറ്റം',
      chart_subtitle: 'ആകെ CO₂ ബഹിർഗമനത്തിലെ സ്ഥാനം, 1990-ലും 2024-ലും',
      alt_text: 'സ്ഥാനങ്ങളുടെ ചാർട്ട്: ഇന്തോനേഷ്യ 25-ാം സ്ഥാനത്തുനിന്ന് ആറാം സ്ഥാനത്തേക്ക്, ഇറാൻ 20-ാം സ്ഥാനത്തുനിന്ന് ഏഴാം സ്ഥാനത്തേക്ക്.',
      caveat: 'മറ്റുള്ളവർ താഴുമ്പോഴും സ്ഥാനം ഉയരാം; ആകെ കണക്കും നോക്കണം.',
      facts_used: [],
      glossary: { ഇന്തോനേഷ്യ: 'Indonesia', ഇറാൻ: 'Iran', 'സൗദി അറേബ്യ': 'Saudi Arabia', 'ദക്ഷിണ കൊറിയ': 'South Korea', തുർക്കി: 'Turkey' },
    },
  },
}
